export { default as Header } from "./header/header"
export { default as Footer } from "./footer/footer"
export { default as GalleryProduct } from "./GalleryProduct/GalleryProduct"
export { default as CardInfo } from "./cardInfo/cardInfo"
export { default as Print } from "./products/print"
export { default as Poster } from "./products/Poster"
export { default as Invoice } from "./products/invoice"
