export { default as Header } from "./header/header"
export { default as Footer } from "./footer/footer"
export { default as GalleryProduct } from "./GalleryProduct/GalleryProduct"
export { default as CardInfo } from "./cardInfo/cardInfo"
export { default as Print } from "./products/print"
export { default as Poster } from "./products/Poster"
export { default as Invoice } from "./products/invoice"
export { default as ImgInformation } from "./imageInformation/imageInformation"
export { default as InfoCompany } from "./infoCompany/infoCompany"
export { default as Location } from "./location/location"
export { default as Layout} from "./layout/layout"
export { default as OurService} from "./OurService/ourService"
